// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvwZHXs-Y2-vnF8t2KWfVs1ODb81DzWk0',
    appId: '1:107781542059:web:0dd1b1aa86d6f8e6c9e7ee',
    messagingSenderId: '107781542059',
    projectId: 'quick-ticket-maker-sandbox',
    authDomain: 'quick-ticket-maker-sandbox.firebaseapp.com',
    storageBucket: 'quick-ticket-maker-sandbox.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXwPrpuJK3CGVEuJ-hYEp9N4Y99gbmHZg',
    appId: '1:107781542059:android:ad44b29439001b91c9e7ee',
    messagingSenderId: '107781542059',
    projectId: 'quick-ticket-maker-sandbox',
    storageBucket: 'quick-ticket-maker-sandbox.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ8eqQxRHND9mMkuCWmDTAH4vBgFD2H7E',
    appId: '1:107781542059:ios:3aee97098aa23948c9e7ee',
    messagingSenderId: '107781542059',
    projectId: 'quick-ticket-maker-sandbox',
    storageBucket: 'quick-ticket-maker-sandbox.firebasestorage.app',
    iosClientId: '107781542059-s9csu7kamfsavn0n0c30eda68ikrgma6.apps.googleusercontent.com',
    iosBundleId: 'com.injectgroup.ticketMaker',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ8eqQxRHND9mMkuCWmDTAH4vBgFD2H7E',
    appId: '1:107781542059:ios:3aee97098aa23948c9e7ee',
    messagingSenderId: '107781542059',
    projectId: 'quick-ticket-maker-sandbox',
    storageBucket: 'quick-ticket-maker-sandbox.firebasestorage.app',
    iosClientId: '107781542059-s9csu7kamfsavn0n0c30eda68ikrgma6.apps.googleusercontent.com',
    iosBundleId: 'com.injectgroup.ticketMaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvwZHXs-Y2-vnF8t2KWfVs1ODb81DzWk0',
    appId: '1:107781542059:web:8d8c50852494d2e4c9e7ee',
    messagingSenderId: '107781542059',
    projectId: 'quick-ticket-maker-sandbox',
    authDomain: 'quick-ticket-maker-sandbox.firebaseapp.com',
    storageBucket: 'quick-ticket-maker-sandbox.firebasestorage.app',
  );
}
